version: "3.9"
services:
  database:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - database
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URI: mongodb://database:27017/dingus?retryWrites=true&writeConcern=majority
      TOKEN: ${TOKEN}
      CLIENT_ID: ${CLIENT_ID}

volumes:
  mongodb-data:
