version: "3.9"
services:
  database:
    restart: always
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - private

  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - database
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database:27017
      DB_NAME: necrobot
    networks:
      - private

  prometheus:
    image: prom/prometheus:v2.21.0
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    networks:
      - private

  grafana:
    image: grafana/grafana:7.5.7
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./configs/grafana:/etc/grafana
      - grafana-data:/var/lib/grafana
    networks:
      - public
      - private

volumes:
  mongodb-data:
  prometheus-data:
  grafana-data:

networks:
  public:
  private: