version: "3.9"
services:
  database:
    restart: always
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    volumes:
      - necrobot-database-data:/data/db

  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - database
    restart: always
    ports:
      - "8085:8085"
    environment:
      DB_HOST: database:27017
      DB_NAME: necrobot

  prometheus:
    image: prom/prometheus:v2.21.0
    restart: always
    ports:
      - "9000:9090"
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.5.7
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./configs/grafana:/etc/grafana
      - grafana-data:/var/lib/grafana

volumes:
  necrobot-database-data:
  prometheus-data:
  grafana-data:
