version: "3.9"
services:
  database:
    restart: always
    image: 'mongo:latest'
    ports:
      - "27017:27017"

  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - database
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database:27017
      DB_NAME: necrobot