{
 "title": "NecroBot",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Command Times",
   "type": "graph",
   "description": "The amount of time it takes for NecroBot to process a command.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bot_command_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Reminders",
   "type": "graph",
   "description": "The total number of reminders registered.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bot_reminder_count" }
   ]
  },
  {
   "title": "Guilds",
   "type": "graph",
   "description": "The number of Guilds that NecroBot is apart of.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bot_guild_count" }
   ]
  },
  {
   "title": "Late Reminders",
   "type": "graph",
   "description": "The total amount of times that NecroBot was late for a reminder.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bot_late_count" }
   ]
  }
 ]
}