name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: ghcr.io/yukitsune/dingus-bot:${{ github.event.release.tag_name }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build \
          --file Dockerfile \
          --tag ${{ env.IMAGE_NAME }} \
          .
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.12.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}
